### ISSUE TITLE
Inputs losing focus on computed schema

### ISSUE THREAD

**Issue by marina-mosti** [formvuelate/formvuelate#142]
Based on #141 
Reported by @D3m1urg0

You can reproduce it directly in the codesandbox i provided: (but i get the same result also on my local project)
if you insert any value inside the textfields they will loose the focus at each input event (you can just type one letter then you need to select the field again)

I tested it also commenting the plugins options and everything works as intended then it should be some kind of regression from the last fix.

**Comment by marina-mosti** [comment]
Hey @logaretm mind taking a look? Seems when I comment out the vee-validate plugin it works, but with it the bug described here is present. 

https://codesandbox.io/s/test-reactivity-formvuelate-rpj1e?file=/src/App.vue

**Comment by logaretm** [comment]
@marina-mosti Sharing my findings, for some reason when binding the `onUpdate:modelValue` to the rendered component the whole form re-renders.

If I skip doing that it works fine, since vee-validate integration uses the composition API strictly, it doesn't affect rendering or events handling. Not sure how this could be fixed.

When calling `attrs['onUpdate:modelValue'](anyVal)` it causes the whole form to re-render as well, keys on the generated components doesn't work as I can already see you assign keys to the generated fields.

Maybe a key is needed on the root form component?

**Comment by marina-mosti** [comment]
Hey @d3m1urg0 we found the problem, and should be issuing a fix soon. Thanks for pointing us to the problem again

**Comment by marina-mosti** [comment]
Fixed by: https://github.com/formvuelate/formvuelate-plugin-vee-validate/pull/10
