### ISSUE TITLE
Schema condition reset 

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#198]
When using [schema condition](https://formvuelate.js.org/guide/advanced-schema.html#conditionally-displaying-an-element-within-the-schema) i think when the condition result gets to false then any previous inputed value should have destroyed/cleared.

Example:

```
const formData = ref({});
useSchemaForm(formData);

const formSchema = {
  example: {
    component: FormSelect,	
    label: "Choose...",
    options: ["1", "2"]
  }
  one: {
    component: FormText,
    label: "One",
    condition: model => model.example === '1'
  },
  two: {
    component: FormText,
    label: "Two",
    condition: model => model.example === '2'
  }
}
```

Steps:
1. As "1" is selected on load the "one" FormText is visible. Write something in it.
2. In FormSelect choose "2" and then "two" FormText gets visible, but the value that we write in "one" FormText is still in the
`formData`.

Also here:
https://formvuelate.js.org/examples/#conditional-fields-with-schema
when `aField` or `bField` data added it stays there forever without manualy deleting it.

**Comment by marina-mosti** [comment]
Hello @erkage I'm on the fence with this one, maybe @tzhelyazkova and @logaretm want to weight in on this one.

I'm leaning towards agreeing that the schema property should probably be removed, with the exception of `preventModelCleanupOnSchemaChange` being `true`.

I'll get back to this when time permits with the pertinent change/docs clarification

**Comment by logaretm** [comment]
I think this is mostly a "product decision" because depending on the use case it will benefit some over the other. 

let's say when a field is unmounted, its value path will be destroyed (removed) from the model. This is desirable for conditional fields where a field is present depending on some condition.

This becomes undesirable if someone is taking advantage of computed schema to create a stepped form. For example, if `step = 1` it will return a set of fields, otherwise another set. For that use-case keeping the values is desirable.

I agree with @marina-mosti that the property should be cleaned up by default, and a configuration seems suitable to handle the other use-case.
