### ISSUE TITLE
Nested conditions in nested schemas not working

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#205]
If i use an already conditioned model in a condition it gives `TypeError: Cannot read property 'model' of undefined`.

Example:
https://codesandbox.io/s/fvl-conditional-schema-with-schema-condition-3x-forked-rw5vo?file=/src/App.vue:1540-1599

Tried versions:
3.2.1 - 3.2.3

**Comment by marina-mosti** [comment]
Thanks @erkage will investigate

**Comment by marina-mosti** [comment]
Hey @erkage I found the problem. The solution is to change your condition to 

```js
return model.first?.second?.type2 === "C";
```

FormVueLate returns the `model` as it currently is (unwrapped). This model is what you created using `useSchemaForm`. Since there are no pre-defined values, neither `first` nor `second` exist yet in the model. Thus, you have to check first if these properties even exist in your function before trying out to check for an equality to a value `C`.

The library doesn't deeply analyze the schema to pre-construct the model for you, it either constructs it lazily as the user fills the form, or uses as a template what you predefined in the `useSchemaForm` model instantiation.

So another solution would be to state in your starting model:

```js
const form = ref({
      first: {
        second: {}
      }
    });
```

**Comment by erkage** [comment]
Hey @marina-mosti,
OMG...makes sense! I'd just overthink it and thought it's a complicated core issue 🙂 .
Thanks for checkin and big 👍  for the docs 🙂 .
