### ISSUE TITLE
Add Support for (repeatable) Field Groups

### ISSUE THREAD

**Issue by digitalkaoz** [formvuelate/formvuelate#250]
i really would like to see something like this implemented https://vueformulate.com/guide/inputs/types/group/#repeatable-groups

so basically a nested schema which can be repeated and constraints like `min_items=1, max_items=10`

the schema might look like this:

```js
{
  users: {
     type: "group",
     min: 1,
     max: 0, //infinity,
     repeatable: true,
     schema: {
         name: {type:"string", label:"Name"},
         age: {type:"string", label:"Age", config:{type:"number"}},
         email: {type:"string", label:"Email"},
     }
  }
}
```

it even could be nested i guess:

```js
{
  users: {
     type: "group",
     min: 1,
     max: 0, //infinity,
     repeatable: true,
     schema: {
         name: {type:"string", label:"Name"},
         age: {type:"string", label:"Age", config:{type:"number"}},
         email: {
            type: "group",
            repeatable:true,
            schema: {
               email: {type:"string", label:"Email"},
               type: {type:"select", options:["Work", "Private"]}
            }
         },
     }
  }
}
```

im not sure if its possible with the current architecture but would be the last missing piece to have really powerful schema forms

**Comment by marina-mosti** [comment]
This I think can already be achieved by using a `computed` schema, where some sort of flag/ref on your code that keeps a count of how many users should appear updates the computed schema and more fields appear.

https://codesandbox.io/s/fvl-conditional-schema-with-schema-condition-3x-q7uoo

I don't think we can provide it out of the box on the schema as you suggest because that would more than likely have to assume some architecture, or we would have to provide an out of the box component to group the fields and allow the user to click to add more - which goes against the bring-you-own-components architecture of FormVueLate. 

Formulate is different that way, and is very good at providing its own components.

Ill keep it in mind though in case I can figure out some manner of solution that requires no intermediate grouping component, but you should def be able to solve it with a computed :)

**Comment by kishan93** [comment]
@marina-mosti I am generating multiple fields using a computed property


```
for (let i = 0; i < sizeCount.value; i++) {
...
  [
    {
            model: `size[${i}]['width']`,
            component: FormText,
            type: 'number',
            placeholder: 'Width(inches)',
            containerClass: 'col-span-3 mt-4 sm:col-span-1',
            validations: yup.number().required(),
    },
    {
        model: `size[${i}]['height']`,
        component: FormText,
        type: 'number',
        placeholder: 'Height(inches)',
        containerClass: 'col-span-3 mt-4 sm:col-span-1',
        validations: yup.number().required(),
    },
  ]
}
...
```

but I am facing difficulties storing those values in the model.
and also unable to remove an element at the specified index.

am I missing something ? is there another way to assign value to a model?
